#!/usr/bin/env python3
"""gen_objects.py — objects.json -> FlightGear .stg tree + ground-station .kml.

objects.json is the single source of truth for custom scenery objects (markers,
targets, the ortho ground quad). This emits BOTH:

  * Objects/<10x10>/<1x1>/<index>.stg   — FlightGear static objects, one file
    per scenery tile, tile index COMPUTED from each object's lat/lon (objects
    may span tiles). run.sh bind-mounts the tree under Scenery/Objects/ so
    edits apply on the next fgfs restart. NOTE (proven on this FG build): flat
    ground-plane quads placed via static .stg LOAD but never RENDER — the
    runtime /ortho auto-place (nasal/addobj.nas) is what draws them. Solid
    models (boxes, buoys) render fine from the .stg.
  * objects.kml — a marker overlay for the ground station (QGC: Plan view ->
    load KML). QGC renders KML *polygons*, NOT standalone Point pins, and its
    importer only reliably handles plain top-level <Polygon> elements — so each
    object becomes a small clamped square. Objects with kml_m<=0 are skipped.

objects.json schema (see assets.example/objects.json):
  {
    "models":  { "<name>": {"path": "Models/...xml", "stg": "OBJECT_SHARED"} },
    "objects": [ {"id": .., "model": .., "lat": .., "lon": ..,
                  "elev_m": .., "hdg": .., "pitch": .., "roll": ..,
                  "kml_m": <marker square edge, m; 0=skip>} ]
  }

Usage:
  gen_objects.py [--json objects.json] [--out <assets-dir>]
  (defaults: --json ./objects.json, --out = the json's directory)

.stg line format (lon BEFORE lat):
  <OBJECT_STATIC|OBJECT_SHARED> <model-path> <lon> <lat> <elev_m> <hdg> <pitch> <roll>
"""
import argparse
import json
import math
import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
import fg_tiles  # noqa: E402

DEFAULT_KML_M = 25.0


def main():
    ap = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    ap.add_argument("--json", default="objects.json", help="objects.json path")
    ap.add_argument("--out", default=None,
                    help="assets dir to write Objects/ + objects.kml into "
                         "(default: the json's directory)")
    args = ap.parse_args()

    src = os.path.abspath(args.json)
    if not os.path.isfile(src):
        sys.exit(f"ERROR: no such objects file: {src}")
    out = os.path.abspath(args.out or os.path.dirname(src))

    with open(src) as f:
        cfg = json.load(f)
    models = cfg["models"]
    objs = cfg["objects"]
    for o in objs:  # validate at the boundary, fail fast with the object id
        if o["model"] not in models:
            sys.exit(f"ERROR: object {o.get('id', '?')} references unknown model "
                     f"'{o['model']}'")
        for k in ("lat", "lon"):
            if not isinstance(o.get(k), (int, float)):
                sys.exit(f"ERROR: object {o.get('id', '?')} missing numeric '{k}'")

    # ---- group objects by computed scenery tile, one .stg per tile ----
    tiles = {}
    for o in objs:
        rel = fg_tiles.stg_relpath(o["lon"], o["lat"])
        tiles.setdefault(rel, []).append(o)

    for rel, tile_objs in sorted(tiles.items()):
        stg_path = os.path.join(out, "Objects", rel)
        os.makedirs(os.path.dirname(stg_path), exist_ok=True)
        lines = ["# generated by gen_objects.py from %s -- DO NOT EDIT BY HAND"
                 % os.path.basename(src),
                 "# FlightGear static objects for tile %s"
                 % os.path.splitext(os.path.basename(rel))[0]]
        for o in tile_objs:
            m = models[o["model"]]
            lines.append("%s %s %.6f %.6f %g %s %s %s" % (
                m["stg"], m["path"], o["lon"], o["lat"], o.get("elev_m", 0),
                o.get("hdg", 0), o.get("pitch", 0), o.get("roll", 0)))
        lines.append("")
        with open(stg_path, "w") as f:
            f.write("\n".join(lines))
        print(f"wrote {stg_path} ({len(tile_objs)} objects)")

    # ---- ground-station KML (square polygons, QGC-compatible) ----
    kml_path = os.path.join(out, "objects.kml")
    kml = ['<?xml version="1.0" encoding="UTF-8"?>',
           '<kml xmlns="http://www.opengis.net/kml/2.2"><Document>',
           '<name>sim custom objects</name>',
           '<Style id="simobj"><LineStyle><color>ff0000ff</color><width>3</width></LineStyle>'
           '<PolyStyle><color>553333ff</color></PolyStyle></Style>']
    n_kml = 0
    for o in objs:
        size = float(o.get("kml_m", DEFAULT_KML_M))
        if size <= 0:  # whole-area quads / no-marker objects
            continue
        lon, lat = o["lon"], o["lat"]
        dlat = (size / 2.0) / 111320.0
        dlon = (size / 2.0) / (111320.0 * math.cos(math.radians(lat)))
        ring = " ".join("%.7f,%.7f,0" % c for c in [
            (lon - dlon, lat - dlat), (lon + dlon, lat - dlat),
            (lon + dlon, lat + dlat), (lon - dlon, lat + dlat),
            (lon - dlon, lat - dlat)])
        kml.append(
            '<Placemark><name>%s</name><description>%s (%s)</description>'
            '<styleUrl>#simobj</styleUrl>'
            '<Polygon><altitudeMode>clampToGround</altitudeMode><outerBoundaryIs>'
            '<LinearRing><coordinates>%s</coordinates></LinearRing>'
            '</outerBoundaryIs></Polygon></Placemark>' % (
                o["id"], o["model"], o.get("note", ""), ring))
        n_kml += 1
    kml.append('</Document></kml>')
    with open(kml_path, "w") as f:
        f.write("\n".join(kml) + "\n")
    print(f"wrote {kml_path} ({n_kml} polygon(s); QGC loads the FIRST one by default)")


if __name__ == "__main__":
    main()
